#!/bin/bash

################
#Author:Aashna Mahajan
#Date:11/07
#Version:v1


#This script will report aws resource usage
###################

#Aws S3
#Aws Ec2
#Aws lambda
#Aws IAM users
#direct every output to a file using >

set -x 

#list s3 buckets
echo "print list of s3 buckets"
aws s3 ls > resourceTracker

#list EC2 instances
echo "print list of ec2 instances"
aws ec2 describe-instances | jq '.Reservations[].Instances[].InstanceId'

#list aws lambda
echo "print list of lambda functions"
aws lambda list-functions >> resourceTracker:q!

#list IAM users
echo "print list of IAM users"
aws iam list-users




